# frontend/docker-compose.yml
# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ai-studio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"

networks:
  frontend-network:
    driver: bridge
